Numpy - Indexing and Selection 
In this notebook, we will go through the following concepts:
- Grabbing a single element
- Grabbing a slice of elements
- Broadcast selection
- Indexing and selection in 2-d arrays
- Conditional Selection


In [1]:
# so lets first import numpy 
import numpy as np 


In [5]:
# now i am to create an array with a step size of 4
array = np.arange(0,160,4)
array

array([  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,
        52,  56,  60,  64,  68,  72,  76,  80,  84,  88,  92,  96, 100,
       104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 148, 152,
       156])

In [6]:
# just as normal arrays in any language,if we want to grab an element we can pass its index
array[10]

40

In [7]:
# now lets select multiple indexs
# note that the last index is not included that means only values till 10 index
array [1:11]

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [8]:
array[:11]

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [9]:
array[10:]

array([ 40,  44,  48,  52,  56,  60,  64,  68,  72,  76,  80,  84,  88,
        92,  96, 100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140,
       144, 148, 152, 156])

In [11]:
# The difference between a python list and numpy array is the ability to broadcast
array[0:5] = 10
array

array([ 10,  10,  10,  10,  10,  20,  24,  28,  32,  36,  40,  44,  48,
        52,  56,  60,  64,  68,  72,  76,  80,  84,  88,  92,  96, 100,
       104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 148, 152,
       156])

In [14]:
# important point here is that broadcast can effect the original array
# here is a small code to show that 
# first lets create a subarray or slice of original array
slice_array = array[0:11] 
slice_array

array([10, 10, 10, 10, 10, 20, 24, 28, 32, 36, 40])

In [17]:
# lets know use broadcast to change all slice_array values to 80
slice_array[:]  = 80
slice_array

array([80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80])

In [18]:
# now lets print the original array 
# you can see that the broadcast on subarray has effected the original array
array 

array([ 80,  80,  80,  80,  80,  80,  80,  80,  80,  80,  80,  44,  48,
        52,  56,  60,  64,  68,  72,  76,  80,  84,  88,  92,  96, 100,
       104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 148, 152,
       156])

In [20]:
# what if you do not want broadcast to effect the original array 
# in that case you need to use the copy method
slice_array_new = array.copy()
slice_array_new

array([ 80,  80,  80,  80,  80,  80,  80,  80,  80,  80,  80,  44,  48,
        52,  56,  60,  64,  68,  72,  76,  80,  84,  88,  92,  96, 100,
       104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 148, 152,
       156])

In [22]:
slice_array_new[:11] = 90
slice_array_new

array([ 90,  90,  90,  90,  90,  90,  90,  90,  90,  90,  90,  44,  48,
        52,  56,  60,  64,  68,  72,  76,  80,  84,  88,  92,  96, 100,
       104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 148, 152,
       156])

In [24]:
# see the original array remains the same
array

array([ 80,  80,  80,  80,  80,  80,  80,  80,  80,  80,  80,  44,  48,
        52,  56,  60,  64,  68,  72,  76,  80,  84,  88,  92,  96, 100,
       104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 148, 152,
       156])

In [26]:
# lets now work on 2d arrays 
array_2d = np.array([[10,20],[30,40],[50,60]])
array_2d

array([[10, 20],
       [30, 40],
       [50, 60]])

In [28]:
# to view rows and columns, we use shape method
array_2d.shape

(3, 2)

In [31]:
# lets grab only the rows, run them separately to get each row
array_2d[0]
array_2d[1]
array_2d[2]

array([50, 60])

In [35]:
# to grab the first column
array_2d[:,0]

array([10, 30, 50])

In [37]:
# for specific values 
array_2d[1,1]

40

In [38]:
# there are different conditions that you can apply on numpy array 
array

array([ 80,  80,  80,  80,  80,  80,  80,  80,  80,  80,  80,  44,  48,
        52,  56,  60,  64,  68,  72,  76,  80,  84,  88,  92,  96, 100,
       104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 148, 152,
       156])

In [41]:
# for example in the above array, you only want numbers greater than 100
bool_array = array > 100 
bool_array


array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [42]:
array[bool_array]

array([104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 148, 152,
       156])

In [43]:
# another way to do the above task
array[array>100]

array([104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 148, 152,
       156])