<a href="https://colab.research.google.com/github/Adeelzafar/Adeelzafar/blob/main/A_crash_course_on_Numpy_3_Numpy_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# In this notebook, we will see different numpy operations

In [2]:
import numpy as np

In [3]:
# Lets create a numpy array 
array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Performing airthemtic operations on array
array + 5
 

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
array - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [7]:
array * 6

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54])

In [8]:
array + array 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
# Numpy comes with some basic mathematical functions as well

np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [10]:
np.square(array)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [11]:
np.sin(array)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [12]:
np.log(array)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [13]:
# Numpy also supports some statistical operations
array.sum()

45

In [14]:
array.mean()

4.5

In [15]:
array.max()

9

In [16]:
array.min()

0

In [17]:
array.std()

2.8722813232690143

In [21]:
# Lets now create a 2D array 
array2d = np.arange(1,26).reshape(5,5)
print(array2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [23]:
array2d.shape

(5, 5)

In [24]:
#Peforming sum across the rows, The below command gives the each row of first column
array2d.sum(axis=0)

array([55, 60, 65, 70, 75])

In [26]:
#Peforming sum across the columns
array2d.sum(axis=1)

array([ 15,  40,  65,  90, 115])