<a href="https://colab.research.google.com/github/Adeelzafar/Adeelzafar/blob/main/A_crash_course_of_Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

NumPy is a powerful linear algebra library for Python. What makes it so important is that almost all of the libraries in the PyData ecosystem (pandas, scipy, scikit-learn, etc.) rely on NumPy as one of their main building blocks. 

NumPy is also incredibly fast, as it has bindings to C libraries. 

In [30]:
#importing numpy
import numpy as np

In [2]:
mylist = [2,3,4]

In [5]:
#Transforming a list into numpy array
np.array(mylist)

array([2, 3, 4])

In [6]:
mylist1 = [[2,3],[3,2]]

In [7]:
np.array(mylist1)

array([[2, 3],
       [3, 2]])

In [9]:
# we can arrange an array using arrange method in numpy
np.arange(0,50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [10]:
# you can also define a step size for arranging array, This will be the third argument
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [14]:
#you can also create an array of zeros using the following command. Notice that the first argument is the shape of array
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
#similar to np zeros, you can create np ones
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
#numpy can also be used to create an identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
#numpy also supports alot of functions to create random arrays 
# here distribution is between 1 and 0
np.random.rand(4)

array([0.46059763, 0.89529564, 0.38056536, 0.32629814])

In [23]:
# to get a random matrix
np.random.rand(3,3)

array([[0.23827979, 0.39098507, 0.08438525],
       [0.15441547, 0.57303686, 0.23827404],
       [0.79631738, 0.0810346 , 0.41599978]])

In [26]:
# if you want to generate a random salary between two salary numbers
np.random.randint(100, 1000)

959

In [29]:
#if you want similar random numbers for different purposes, you can use the seed function
np.random.seed(30)
np.random.rand(2,2)

array([[0.64414354, 0.38074849],
       [0.66304791, 0.16365073]])

In [33]:
array = np.arange(25)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
# reshaping an array, lets first check the shape of array
array.shape

(25,)

In [38]:
array.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
# we can also identify the maximum, minimun number from an array and also its index using following
array.max()

24

In [41]:
array.min()

0

In [42]:
array.argmax()

24

In [43]:
array.argmin()

0