<a href="https://colab.research.google.com/github/Adeelzafar/Intro-to-Data-Science-Bootcamp/blob/main/Lecture_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Intro:
  - Homework 1 will be released next Wednesday
2. Lec 2: Matplotlib
3. Lec 3: Numpy
  - Vectorization
  - Boardcast
  - Identify Matrix 
  - Indexing and Slicing
  - Fancy Array
  - Reduction Operation

# Basic Section (Start)


In [ ]:
import numpy as np

## Numpy (Review)

Main object type is `np.array`

Many ways to create it,

One way is to convert a python list

In [ ]:
python_list = [ 1,2,3 ]
arr = np.array(python_list)   
arr

array([1, 2, 3])

In [ ]:
arr**2

array([1, 4, 9])

In [ ]:
python_list**2

TypeError: ignored

In [ ]:
#arr.__pow__
python_list.__pow__

AttributeError: ignored

Many times a list comprehension is used to create a list and then converted to a array

In [ ]:
python_list_pow = [ i**2 for i in python_list if i != 1] #Add if statement for conditional result
python_list_pow

[4, 9]

### Exercise (In Lec)
Create a numpy array that contain  intergers i  such that  0<i<100 and $2^i$ has the last digit 6

In [ ]:
np.array( [  i  for i in range(1,100)   if (2**i)%10 == 6 ]  )

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68,
       72, 76, 80, 84, 88, 92, 96])

Create a 2D numpy array $A$ (5,10) such that $A_{ij} = i\times j$

In [ ]:
np.array( [[ i*j for i in range(10)] for j in range(5)] )

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36]])

## Another way to create a numpy array is with initializing functions

- np.zeros
- np.ones
- np.arange

These functions along with `reshape` can be used to create initial matrix without any for loops

In [ ]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((10,10)) * 3

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [ ]:
np.arange(2,10, 2) #equivalent to range(2,10,2)

array([2, 4, 6, 8])

### Exercise (In Lec)

Create an array of first 10 powers of 2

In [ ]:
#Answer:
2**(np.arange(10))

array([  1,   2,   4,   8,  16,  32,  64, 128, 256, 512])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 1D vs 2D array
np.arange(10)*np.arange(10)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
np.arange(10).reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
np.arange(10).reshape(10,1) * np.arange(10)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81]])

### Distinction between numpy 1D arrays and numpy 2D arrays

This tends to cause a lot of confusion for new numpy users.
Follow the below examples carefully to understand the distinction.

In [ ]:
Z = np.zeros(10)
print(Z)
Z.shape

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


(10,)

In [ ]:
# Create 2D array by dimension
Z = np.zeros((10,1))
print(Z)
Z.shape

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


(10, 1)

In [ ]:
# Create 2D array by reshape
Z = np.zeros(10).reshape(10,1)
print(Z)
Z.shape

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


(10, 1)

In [ ]:
Z.squeeze()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# squeeze Remove axes of length one
Z = np.zeros(6).reshape(1, 1, 2,3)
print(Z.shape)
Z.squeeze().shape

(1, 1, 2, 3)


(2, 3)

In [ ]:
Mat = np.random.randn(10,10)

In [ ]:
# (N, M) @ (M, K) = (N, K)
Z = np.arange(10).reshape(10,1)
Mat@Z

array([[  0.30769775],
       [  9.75877965],
       [ -9.70168534],
       [-20.68560714],
       [ -6.98638704],
       [ -3.76850708],
       [ 24.26201462],
       [ 14.59006322],
       [ 13.377931  ],
       [ 10.99363161]])

In [ ]:
Z = np.arange(10).reshape(1,10)

print(Mat.shape)
print(Z.shape)
Mat@Z # (10, 10) @ (1, 10) NOT WORKING

(10, 10)
(1, 10)


ValueError: ignored

In [ ]:
# array variable is also a pointer
x = np.zeros((5,5))
print(x[1,1])
y = x.copy()
x[1,1]= 2
y

0.0


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Array Broadcasting

Normally you only do arithmetic operations between arrays of the same dimension 

The smaller array is “broadcast” across the larger array so that they have compatible shapes by dimension.

In [ ]:
a = np.ones(3)
b = np.ones((3,1))
c = np.ones((3,3))
d = np.ones((6,3))
print(a, '\n')
print(b,'\n')
print(c,'\n')
print(d,'\n')

[1. 1. 1.] 

[[1.]
 [1.]
 [1.]] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 



In [ ]:
# c + 2
# c + c
# d + a
c + b

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [ ]:
np.ones((6,1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [ ]:
np.ones((1,5))

array([[1., 1., 1., 1., 1.]])

In [ ]:
np.ones((6,1)) + np.ones((1,5))

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [ ]:
X = np.arange(4).reshape(-1,1)*10
Y = np.arange(3).reshape(1,-1)
print(X.shape)
print(Y.shape,'\n')
print(X,'\n')
print(Y,'\n')
X+Y

(4, 1)
(1, 3) 

[[ 0]
 [10]
 [20]
 [30]] 

[[0 1 2]] 



array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
np.arange(4).reshape(-1,4)

array([[0, 1, 2, 3]])

![](http://scipy-lectures.org/_images/numpy_broadcasting.png)

### Exercise (In-Lecture)
create a 2D numpy array $A$ (shape = (5,10) ) such that $A_{ij} = i\times j$, but without using list comprehensions. Use broadcasting instead


In [ ]:
np.arange(5).reshape(-1, 1) * np.arange(10).reshape(1, -1)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36]])

Use array broadcasting to create a (10,10) numpy array with values
$$ A_{ij} = 2^i + j $$

In [ ]:
# 2**(np.arange(10).reshape(-1,1)) + np.arange(10).reshape(1,-1)

# Basic Section (End)

## Matrix creation

There are some functions to create standard matrices

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# np.diag: Extract a diagonal or construct a diagonal array.
M = np.diag(np.arange(10))#.reshape(5,20)
M

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.diag(M)

array([0, 0, 0, 0, 0])

In [ ]:
# Transpose of the matrix
A = np.arange(15).reshape(5,3)
print(A.shape)
A

(5, 3)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
A.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [ ]:
A.transpose()

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [ ]:
np.eye(5)

In [ ]:
np.random.rand(5,5)

array([[0.6630782 , 0.26332238, 0.020651  , 0.75837865, 0.32001715],
       [0.38346389, 0.58831711, 0.83104846, 0.62898184, 0.87265066],
       [0.27354203, 0.79804683, 0.18563594, 0.95279166, 0.68748828],
       [0.21550768, 0.94737059, 0.73085581, 0.25394164, 0.21331198],
       [0.51820071, 0.02566272, 0.20747008, 0.42468547, 0.37416998]])

In [ ]:
np.random.seed(0) #control the random state
np.random.rand(5,5)

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443]])

### Exercise (Post Lecture)

Create this matrix   

```python
array([[5., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 4., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 3., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 3., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 4., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 5.]])
```

In [ ]:
# np.diag(np.abs(4 - np.arange(11))) + 1

## Array Indexing and Slicing

In [ ]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[5]

5

In [ ]:
arr[-3]

7

In [ ]:
arr[3:7]

array([3, 4, 5, 6])

In [ ]:
arr[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[0:-3]

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
arr[0:6:2] #similar as range(0,6,2)

array([0, 2, 4])

In [ ]:
arr[5:0:-2]

array([5, 3, 1])

In [ ]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
arr[:] 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.array(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = 10*np.arange(6).reshape(-1,1)+np.arange(6)
a[4:, 4:]

array([[44, 45],
       [54, 55]])

Can use all the above slicing methods for each dimension of a multidemnsional array
![](http://scipy-lectures.org/_images/numpy_indexing.png)

try it yourself

In [ ]:
a[2::2,::2]

In [ ]:
a[2::2,::2] = 100000
a

### Exercise (Post-Lecture)
Create the following matrix
```python
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
```

In [ ]:
# a = np.ones((10,10))
# a[2:8, 2:8] = np.zeros((6,6))
# a

Create the following matrix
```python
array([[-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1.,  0.,  1.,  2.,  3.,  4., -1., -1., -1., -1.],
       [-1.,  5.,  6.,  7.,  8.,  9., -1., -1., -1., -1.],
       [-1., 10., 11., 12., 13., 14., -1., -1., -1., -1.],
       [-1., 15., 16., 17., 18., 19., -1., -1., -1., -1.],
       [-1., 20., 21., 22., 23., 24., -1., -1., -1., -1.],
       [-1., 25., 26., 27., 28., 29., -1., -1., -1., -1.],
       [-1., 30., 31., 32., 33., 34., -1., -1., -1., -1.],
       [-1., 35., 36., 37., 38., 39., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.]])
```

In [ ]:
# a = -np.ones((10,10))
# b = np.arange(40).reshape(8,5)
# a[1:9, 1:6] = b
# a

# Fancy Array Indexing

We can use numpy arrays as an index for other numpy arrays

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
idx = np.array([7,-1,2])
idx

array([ 7, -1,  2])

In [ ]:
print(arr[idx])
arr[idx] = -1
arr

[7 9 2]


array([ 0,  1, -1,  3,  4,  5,  6, -1,  8, -1])

In [ ]:
# use bool array
arr<0

array([False, False,  True, False, False, False, False,  True, False,
        True])

In [ ]:
arr[arr<0] = 100#[100,100,100]
arr

array([  0,   1, 100,   3,   4,   5,   6, 100,   8, 100])

For multidimensional array, array indexing works different from slicing

In [ ]:
X = np.zeros((10,10))
X[3:9,3:9]=1
X

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.arange(3,9),np.arange(3,9)

(array([3, 4, 5, 6, 7, 8]), array([3, 4, 5, 6, 7, 8]))

In [ ]:
X = np.zeros((10,10))
X[np.arange(3,9),np.arange(3,9)]=1
X

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# Here is our array, what should we return?
a = 10*np.arange(6).reshape(-1,1)+np.arange(6)
a

In [ ]:
a[np.arange(1,3),np.arange(2,4)]

In [ ]:
import numpy as np
a = 10*np.arange(6).reshape(-1,1)+np.arange(6)
print(a[ (1,2,3,4,5), (0,1,2,3,4)])

In [ ]:
print(a[3:, [0,2,5]])

In [ ]:
mask = np.array([1,0,1,0,0,1], dtype = bool)
print(mask)
a[mask,2]

![](http://scipy-lectures.org/_images/numpy_fancy_indexing.png)

### Exercise (Post - Lecture)
Create the following matrix
```python
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])
```

In [ ]:
# a = np.zeros((10,10))
# a[np.arange(10), np.abs( 9 - 2*np.arange(10))] = 1
# a

### Exercise (Post Lecture)
Write a function to compute the [trace](https://en.wikipedia.org/wiki/Trace_(linear_algebra)) of a square numpy array using fancy array indexing. Compare your implementation to numpy's built-in function `np.trace`.

In [ ]:
# def trace(a):
#   out = 0
#   n = a.shape[0]
#   for i in a[np.arange(n), np.arange(n)]:
#     out += i
#   return out
# trace(a) == np.trace(a)

We can use `np.where`, to get indices of the `True` values in a boolean array

In [ ]:
Y = np.arange(25).reshape(5,5)
print(Y)
Y > 14

np.where(Y>14)
# print(Y)

## Reduction operations

Many reduction functions are available

- np.sum, np.prod
- np.min, np.max
- np.any, np.all

Partial reductions

- np.cumsum, np.cumprod

In [ ]:
X = np.arange(100).reshape(10,10)
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
np.sum(X),np.prod(X)

(4950, 0)

The way to understand the “axis” of numpy sum is it collapses the specified axis. So when it collapses the axis 0 (row), it becomes just one row and column-wise sum.

In [ ]:
# np.sum(X,axis=1)
np.sum(X[:,0], axis = 0)

450

In [ ]:
X.sum(axis = 0)

array([450, 460, 470, 480, 490, 500, 510, 520, 530, 540])

In [ ]:
np.min(X),np.max(X)

In [ ]:
np.min(X,axis=1)

In [ ]:
Y = X<1
Y

array([[ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [ ]:
Y  + 10

array([[11, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [ ]:
np.any(Y,axis=0)

array([ True, False, False, False, False, False, False, False, False,
       False])

In [ ]:
np.all(Y,axis=1)

array([False, False, False, False, False, False, False, False, False,
       False])

All the above functions can be called on the array object directly

In [ ]:
X.max(axis=0)

In [ ]:
# np.cumsum
Y = np.arange(10)
print(Y)
np.cumsum(Y)

In [ ]:
X = np.arange(16).reshape(4,4)
print(X)
np.cumsum(X,axis=1)

Cumulative operations don't change the shape of the array

### Exercise (Post Lecture)

- Find the column with maximum column sum
- For which rows of the matrix, the sum of the first three elements of the row is greater than the sum of the last two elements of the row

In [ ]:
import numpy as np

In [ ]:
np.random.seed(10)
X = np.random.rand(5,5)
(X.sum(axis=0)).argmax()

3

In [ ]:
np.arange(5)[np.sum(X[:,:3],axis = 1) - np.sum(X[:,-2:],axis = 1) > 0]

### Exercise (Post Lecture)
Compute the the moving average of the array `y` created below, with window size 5.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(10)
y = np.cumsum(np.random.rand(100) - 0.5)
plt.plot(y)

In [ ]:
z = np.cumsum(y)
z[5:] = z[5:] - z[:-5]
z /= 5
plt.plot(y)
plt.plot(z)

## Final Exercise (Post Lecture)

Implement the [Conway's game of Life](https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life) using numpy

In [ ]:
# Solution
X = (np.random.rand(100,100)>0.9).astype(int)
import matplotlib.pyplot as plt
plt.imshow(X)

In [ ]:
count =\
X[:-2,:-2] + X[:-2,1:-1] + X[:-2,2::] +\
X[1:-1,:-2] +              X[1:-1,2:] +\
X[2:,:-2] + X[2:,1:-1] +   X[2:,2:]

newX = ((count==3) & (X[1:-1,1:-1]==0)) | (((count==3)|(count==2)) & (X[1:-1,1:-1]==1))
X[:]=0
X[1:-1,1:-1] = newX
plt.imshow(X)